'use strict';

const { v4: uuidv4 } = require('uuid');

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('states', [{
      uuid: uuidv4(),
      state: 'Alabama',
      abbr: 'AL',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Alaska',
      abbr: 'AK',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Arizona',
      abbr: 'AZ',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Arkansas',
      abbr: 'AR',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'California',
      abbr: 'CA',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Colorado',
      abbr: 'CO',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Connecticut',
      abbr: 'CT',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Delaware',
      abbr: 'DE',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Florida',
      abbr: 'FL',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Georgia',
      abbr: 'GA',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Hawaii',
      abbr: 'HI',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Idaho',
      abbr: 'ID',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Illinois',
      abbr: 'IL',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Indiana',
      abbr: 'IN',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Iowa',
      abbr: 'IA',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Kansas',
      abbr: 'KS',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Kentucky',
      abbr: 'KY',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Louisiana',
      abbr: 'LA',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Maine',
      abbr: 'ME',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Maryland',
      abbr: 'MD',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Massachusetts',
      abbr: 'MA',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Michigan',
      abbr: 'MI',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Minnesota',
      abbr: 'MN',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Mississippi',
      abbr: 'MS',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Missouri',
      abbr: 'MO',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Montana',
      abbr: 'MT',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Nebraska',
      abbr: 'NE',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Nevada',
      abbr: 'NV',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'New Hampshire',
      abbr: 'NH',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'New Jersey',
      abbr: 'NJ',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'New Mexico',
      abbr: 'NM',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'New York',
      abbr: 'NY',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'North Carolina',
      abbr: 'NC',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'North Dakota',
      abbr: 'ND',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Ohio',
      abbr: 'OH',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Oklahoma',
      abbr: 'OK',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Oregon',
      abbr: 'OR',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Pennsylvania',
      abbr: 'PA',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Rhode Island',
      abbr: 'RI',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'South Carolina',
      abbr: 'SC',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'South Dakota',
      abbr: 'SD',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Tennessee',
      abbr: 'TN',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Texas',
      abbr: 'TX',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Utah',
      abbr: 'UT',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Vermont',
      abbr: 'VT',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Virginia',
      abbr: 'VA',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Washington',
      abbr: 'WA',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'West Virginia',
      abbr: 'WV',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Wisconsin',
      abbr: 'WI',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      uuid: uuidv4(),
      state: 'Wyoming',
      abbr: 'WY',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('states', null, {});
  },
};
